/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.lth.cs.palcom.browsergui;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author jon
 */
public class AddCommandDialog extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form AddCommandDialog
     */
    public AddCommandDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDirection = new javax.swing.JLabel();
        cmbDirection = new javax.swing.JComboBox();
        btnOk = new javax.swing.JButton();
        //btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setText("Name");

        lblDirection.setText("Direction");

        cmbDirection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "in", "out"}));

        btnOk.setText("Ok");
        btnOk.addActionListener(this);

        //btnCancel.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cmbDirection, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtName)
                    .add(lblDirection, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 37, Short.MAX_VALUE)
                /*.add(btnCancel)*/
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnOk))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblDirection)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmbDirection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 140, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnOk)
                    /*.add(btnCancel)*/))
        );

        pack();
    }

    private static final AddCommandDialog acd = new AddCommandDialog();
    public static String[] getStrings(Component c) {
    	synchronized (acd) {
    		acd.setLocationRelativeTo(c);
    		acd.txtName.setText("");
    		acd.setSize(200, 300);
    		acd.setVisible(true);
    		try {
				acd.wait();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
    		acd.setVisible(false);
    		
    		return new String[] {acd.txtName.getText(), (String) acd.cmbDirection.getSelectedItem()};
    	}
    }
    
    private javax.swing.JButton btnOk;
    //private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cmbDirection;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblDirection;
    private javax.swing.JTextField txtName;
    
	public void actionPerformed(ActionEvent ae) {
		synchronized (acd) {
			acd.notifyAll();
		}
	}
}
