/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.lth.cs.palcom.browsergui;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author jon
 */
public class AddParamDialog extends JDialog implements ActionListener, ChangeListener {

    /**
     * Creates new form NewJPanel
     * @param owner 
     */
    protected AddParamDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        txtValue = new javax.swing.JTextField();
        lblValue = new javax.swing.JLabel();
        txtDefaultValue = new javax.swing.JTextField();
        lblDefaultValue = new javax.swing.JLabel();
        chkRuntime = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();
        btnOk.addActionListener(this);
        btnCancel = new javax.swing.JButton();
        btnCancel.addActionListener(this);

        lblValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblValue.setText("Value");

        lblDefaultValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDefaultValue.setText("Default Value");
        
        lblDefaultValue.setEnabled(false);
        txtDefaultValue.setEnabled(false);

        chkRuntime.setText("Runtime Parameter");
        chkRuntime.addChangeListener(this);

        btnOk.setText("Ok");
        
        btnCancel.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblValue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblDefaultValue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(chkRuntime)
                        .add(0, 193, Short.MAX_VALUE))
                    .add(txtDefaultValue)
                    .add(txtValue))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(btnCancel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnOk))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblValue))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtDefaultValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDefaultValue))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkRuntime)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnOk)
                    .add(btnCancel)))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnCancel;
    private javax.swing.JCheckBox chkRuntime;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblDefaultValue;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtDefaultValue;
	private boolean aborted;
    // End of variables declaration
    
    public synchronized String[] getStrings() {		
		setVisible(true);
		txtValue.setName("");
		txtDefaultValue.setName("");
		chkRuntime.setSelected(false);
		aborted = false;
		setSize(450, 175);
		try {
			wait();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		setVisible(false);
		if (aborted) {
			return new String[] {"","",""};
		} else {
			return new String[] {txtValue.getText(), txtDefaultValue.getText(), String.valueOf(chkRuntime.isSelected())};
		}
	}

	public synchronized void actionPerformed(ActionEvent ae) {
		if (ae.getSource() == btnCancel) {
			aborted = true;
		}
		notifyAll();
	}
	
	public final static AddParamDialog instance = new AddParamDialog(); //Singelton is kinda meh, but whatevah....

	public void stateChanged(ChangeEvent ce) {
		if (ce.getSource() == chkRuntime) {
			boolean runtime = chkRuntime.isSelected();
			txtDefaultValue.setEnabled(runtime);
			lblDefaultValue.setEnabled(runtime);
			lblValue.setText(runtime ? "Parameter name" : "Value");
		}
	}
}
